### ISSUE TITLE
Remove actioncable imported code

### ISSUE THREAD

**Issue by sirwolfgang** [quiltt/quiltt-js#10]
Due to some build issues, we imported the action cable code; The fixes should be unstreamed, so that we can reduce the maintenance risk of this part of the code.

**Comment by rubendinho** [comment]
@sirwolfgang This may be related to: https://github.com/quiltt/quiltt-public/issues/96

I believe all the Apollo stuff should be moved from `@quiltt/core` to `@quiltt/react`. @apollo/client is a React package, and also adds unnecessary dependencies to the non-React core JS package.

**Comment by sirwolfgang** [comment]
@apollo/client is not a react client, it has things to support a react client. https://github.com/apollographql/apollo-client/blob/main/package.json#L66-L86

Anything that an express/node server could also make use of should be in core; but notably a express/node package would also inherent from core.
