### ISSUE TITLE
Add API version headers to Connector GraphQL requests

### ISSUE THREAD

**Issue by zubairaziz** [quiltt/quiltt-js#109]
## Context:

- https://quiltt.slack.com/archives/C2XR19NPR/p1692669846196059

## Problem:

- https://app.honeybadger.io/projects/110217/faults/99567102
- Old API keys erroring with Connector API calls

## Solution:

- Make Connector requests pass a version header,
- Add something like `QUILTT_API_VERSION` to request headers via Apollo `VersionLink`

**Comment by rubendinho** [comment]
Closing this since it's no longer needed thanks to https://github.com/quiltt/quiltt/pull/6695

**Comment by rubendinho** [comment]
Closing this since it's no longer needed thanks to https://github.com/quiltt/quiltt/pull/6695
